[project]
name = "fachpraktikum"
dynamic = ["version"]

dependencies = [
  "fastapi[standard]>=0.120",
  "pydantic",
  "mysql-connector-python"
]

[project.optional-dependencies]
test = [
  "httpx",
  "pytest"
]